name: Forex Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

jobs:
  run-forex:

    runs-on: ubuntu-latest

    steps:

    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas numpy

    - name: Ejecutar script
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python main.py

    - name: Subir CSV generado
      uses: actions/upload-artifact@v4
      with:
        name: forex-data
        path: 20.csv
